# This is the configuration file for the HAPPO algorithm.
seed:
  # whether to use the specified seed
  seed_specify: True
  # seed
  seed: 1
device:
  # whether to use CUDA
  cuda: False
  # whether to set CUDA deterministic
  cuda_deterministic: True
  # arg to torch.set_num_threads
  torch_threads: 1

eval:
  # whether to use evaluation
  use_eval: True
  # number of parallel environments for evaluation
  n_eval_rollout_threads: 1 #5
  # number of episodes per evaluation
  eval_episodes: 10 #10
render:
  # whether to use render
  use_render: False
  # number of episodes to render
  render_episodes: 1
algo:
  share_param: False
  # whether to use a fixed optimisation order
  fixed_order: False
  # GA Parameters
  max_generations: 100
  pop_size: 20
  mutate_prob: 0.05
  retain: 0.2
  random_retain: 0.03
logger:
  # logging directory
  log_dir: "./results_ga"

train:
  model_dir: ""
  n_rollout_threads: 1
  episode_length: 400
